# This is a basic workflow to help you get started with Actions

name: Simple_Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Show secrets
        env:
            snowUsername: ${{ secrets.SN_USERNAME }}
            snowPassword: ${{ secrets.SN_PASSWORD }}
            snowSourceInstance: ${{ secrets.SN_INSTANCE }}
            appSysID: ${{ secrets.SN_APP_SYSID }}
            appScope: ${{ secrets.SN_APP_SCOPE }}
            myName: ${{ secrets.MY_NAME }}
        run: |
            echo $snowUsername
            echo $myName
            
