# This is a basic workflow to help you get started with Actions

name: SN

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [master]
    pull_request:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
        # Purpose of this job is to Apply Remote Changes for the branch triggering 
        # the pipeline build to the Dev instance, then publish the application to 
        # app repo using the template versioning format. 
        name: Publish from Dev
        runs-on: ubuntu-latest

        # Below line can be used to set conditionals for modifying your pipeline as needed.
        # if: ${{ github.event_name == 'pull_request'}}
        steps:
        - name: ServiceNow CI/CD Publish App
          id: publish_app
        #   uses: ServiceNow/sncicd-publish-app@1.0.0
          with:
            versionTemplate: 1.1
            versionFormat: template
          env:
            snowUsername: ${{ secrets.SN_USERNAME }}
            snowPassword: ${{ secrets.SN_PASSWORD }}
            snowSourceInstance: ${{ secrets.SN_INSTANCE }}
            appSysID: ${{ secrets.SN_APP_SYSID }}
            appScope: ${{ secrets.SN_APP_SCOPE }}
            scrt: ${{ secrets }}
          run: |
            echo $snowUsername
            echo $snowPassword
            echo $scrt

            # This is required to pass the version number output from Publish App 
            # to the input for Install App in the next job! This is because the jobs 
            # run on different Linux instances, so without this Install App won't know
            # what to install.
        # outputs:
            # publishversion: ${{ steps.publish_app.outputs.newVersion }}

    deployprod:
    # Purpose of this job is to Install App to a Prod instance. This should only 
    # trigger if the feature branch has been merged to master after a successfully 
    # completed pull request, hence the conditional for push to master. In other words,
    # the first two jobs run on CI, then all three jobs run on CD. 
        name: Deploy to Prod
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' }}
    
        steps:
            - name: ServiceNow CI/CD Install App
              id: install_app_prod
              uses: ServiceNow/sncicd-install-app@1.0.0
              with:
                version: ${{ needs.build.outputs.publishversion }}
              env:
                snowUsername: ${{ secrets.SN_USERNAME }}
                snowPassword: ${{ secrets.SN_PASSWORD }}
                snowInstallInstance: ${{ secrets.SN_INSTANCE }}
                appSysID: ${{ secrets.SN_APP_SYSID }}
                appScope: ${{ secrets.SN_APP_SCOPE }}

            

    
          